version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
  rtmp-server:
    build:
      dockerfile: Dockerfile
      context: ./rtmp-server
    ports:
      - 1935:1935
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 6161:80
